import {
  InstagramAccount,
  ContentPost,
  CreditBalance,
  DashboardStats,
  ActivityItem,
  AnalyticsData,
} from "./types";

export const mockAccounts: InstagramAccount[] = [
  {
    id: "acc-1",
    handle: "@ironpulse_fit",
    displayName: "IronPulse Fitness",
    avatarUrl: "/avatars/fitness.png",
    niche: "fitness",
    status: "connected",
    followers: 24500,
    followersGrowth: 3.2,
    engagementRate: 4.8,
    postsCount: 342,
    lastPostAt: "2026-02-09T10:30:00Z",
    autonomyLevel: "full_auto",
    brandVoice: {
      toneFormality: 30,
      toneHumor: 40,
      toneInspiration: 80,
      contentMix: { educational: 40, inspirational: 30, entertaining: 20, promotional: 10 },
      hashtagStrategy: ["#fitness", "#workout", "#gym", "#fitfam", "#motivation"],
      postsPerDay: 3,
      preferredPostingTimes: ["07:00", "12:00", "18:00"],
    },
  },
  {
    id: "acc-2",
    handle: "@luxe_living_daily",
    displayName: "Luxe Living",
    avatarUrl: "/avatars/luxury.png",
    niche: "luxury",
    status: "connected",
    followers: 89200,
    followersGrowth: 5.1,
    engagementRate: 3.2,
    postsCount: 567,
    lastPostAt: "2026-02-09T08:00:00Z",
    autonomyLevel: "full_auto",
    brandVoice: {
      toneFormality: 70,
      toneHumor: 10,
      toneInspiration: 60,
      contentMix: { educational: 15, inspirational: 40, entertaining: 15, promotional: 30 },
      hashtagStrategy: ["#luxury", "#lifestyle", "#wealth", "#luxurylife", "#rich"],
      postsPerDay: 4,
      preferredPostingTimes: ["09:00", "13:00", "17:00", "21:00"],
    },
  },
  {
    id: "acc-3",
    handle: "@daily_meme_drop",
    displayName: "Daily Meme Drop",
    avatarUrl: "/avatars/memes.png",
    niche: "memes",
    status: "connected",
    followers: 156000,
    followersGrowth: 8.4,
    engagementRate: 7.1,
    postsCount: 1203,
    lastPostAt: "2026-02-09T11:15:00Z",
    autonomyLevel: "semi_auto",
    brandVoice: {
      toneFormality: 5,
      toneHumor: 95,
      toneInspiration: 10,
      contentMix: { educational: 5, inspirational: 5, entertaining: 80, promotional: 10 },
      hashtagStrategy: ["#memes", "#funny", "#memesdaily", "#humor", "#lol"],
      postsPerDay: 5,
      preferredPostingTimes: ["08:00", "11:00", "14:00", "18:00", "21:00"],
    },
  },
  {
    id: "acc-4",
    handle: "@mindset_mogul",
    displayName: "Mindset Mogul",
    avatarUrl: "/avatars/motivation.png",
    niche: "motivation",
    status: "paused",
    followers: 45800,
    followersGrowth: 2.1,
    engagementRate: 5.5,
    postsCount: 289,
    lastPostAt: "2026-02-07T16:00:00Z",
    autonomyLevel: "approval_required",
    brandVoice: {
      toneFormality: 50,
      toneHumor: 15,
      toneInspiration: 95,
      contentMix: { educational: 30, inspirational: 50, entertaining: 10, promotional: 10 },
      hashtagStrategy: ["#motivation", "#mindset", "#success", "#grind", "#hustle"],
      postsPerDay: 3,
      preferredPostingTimes: ["06:00", "12:00", "20:00"],
    },
  },
  {
    id: "acc-5",
    handle: "@techbyte_ai",
    displayName: "TechByte AI",
    avatarUrl: "/avatars/tech.png",
    niche: "tech",
    status: "error",
    followers: 12300,
    followersGrowth: -0.5,
    engagementRate: 2.8,
    postsCount: 98,
    lastPostAt: "2026-02-05T14:30:00Z",
    autonomyLevel: "full_auto",
    brandVoice: {
      toneFormality: 60,
      toneHumor: 30,
      toneInspiration: 40,
      contentMix: { educational: 50, inspirational: 15, entertaining: 25, promotional: 10 },
      hashtagStrategy: ["#tech", "#ai", "#coding", "#programming", "#developer"],
      postsPerDay: 2,
      preferredPostingTimes: ["10:00", "16:00"],
    },
  },
];

export const mockPosts: ContentPost[] = [
  {
    id: "post-1",
    accountId: "acc-1",
    accountHandle: "@ironpulse_fit",
    type: "image",
    status: "queued",
    caption:
      "Your body can stand almost anything. It's your mind that you have to convince. Drop a fire emoji if you're pushing through today!",
    imageUrl: "/posts/fitness-1.png",
    hashtags: ["#fitness", "#motivation", "#gymlife", "#workout"],
    scheduledAt: "2026-02-09T18:00:00Z",
    isRepost: false,
  },
  {
    id: "post-2",
    accountId: "acc-2",
    accountHandle: "@luxe_living_daily",
    type: "carousel",
    status: "queued",
    caption:
      "The art of living well is not about excess - it's about excellence. Swipe through for today's curated luxury finds.",
    imageUrl: "/posts/luxury-1.png",
    hashtags: ["#luxury", "#lifestyle", "#luxuryliving"],
    scheduledAt: "2026-02-09T17:00:00Z",
    isRepost: false,
  },
  {
    id: "post-3",
    accountId: "acc-3",
    accountHandle: "@daily_meme_drop",
    type: "image",
    status: "published",
    caption: "When the code works on the first try. Tag someone who relates!",
    imageUrl: "/posts/meme-1.png",
    hashtags: ["#memes", "#funny", "#relatable", "#programming"],
    scheduledAt: "2026-02-09T11:00:00Z",
    publishedAt: "2026-02-09T11:00:00Z",
    likes: 3420,
    comments: 187,
    reach: 45000,
    impressions: 62000,
    isRepost: true,
    originalCreator: "@code_humor",
  },
  {
    id: "post-4",
    accountId: "acc-1",
    accountHandle: "@ironpulse_fit",
    type: "reel",
    status: "published",
    caption: "5 exercises you're doing WRONG. Save this for your next gym session!",
    imageUrl: "/posts/fitness-2.png",
    hashtags: ["#fitness", "#gymtips", "#workout", "#fitnesstips"],
    scheduledAt: "2026-02-09T07:00:00Z",
    publishedAt: "2026-02-09T07:00:00Z",
    likes: 1890,
    comments: 94,
    reach: 28000,
    impressions: 35000,
    isRepost: false,
  },
  {
    id: "post-5",
    accountId: "acc-4",
    accountHandle: "@mindset_mogul",
    type: "image",
    status: "draft",
    caption:
      "Success is not about perfection. It's about progress. Every small step forward counts.",
    imageUrl: "/posts/motivation-1.png",
    hashtags: ["#motivation", "#success", "#mindset", "#growth"],
    scheduledAt: "2026-02-10T06:00:00Z",
    isRepost: false,
  },
  {
    id: "post-6",
    accountId: "acc-2",
    accountHandle: "@luxe_living_daily",
    type: "image",
    status: "published",
    caption: "Morning views that money can't buy... but a good location can.",
    imageUrl: "/posts/luxury-2.png",
    hashtags: ["#luxury", "#travel", "#views", "#lifestyle"],
    scheduledAt: "2026-02-08T09:00:00Z",
    publishedAt: "2026-02-08T09:00:00Z",
    likes: 5670,
    comments: 234,
    reach: 78000,
    impressions: 95000,
    isRepost: false,
  },
  {
    id: "post-7",
    accountId: "acc-3",
    accountHandle: "@daily_meme_drop",
    type: "image",
    status: "queued",
    caption: "POV: You say 'just one more episode' at 2am",
    imageUrl: "/posts/meme-2.png",
    hashtags: ["#memes", "#relatable", "#funny", "#netflix"],
    scheduledAt: "2026-02-09T21:00:00Z",
    isRepost: false,
  },
  {
    id: "post-8",
    accountId: "acc-5",
    accountHandle: "@techbyte_ai",
    type: "carousel",
    status: "failed",
    caption: "10 AI tools that will change how you work in 2026. Thread below!",
    imageUrl: "/posts/tech-1.png",
    hashtags: ["#ai", "#tech", "#productivity", "#tools"],
    scheduledAt: "2026-02-08T10:00:00Z",
    isRepost: false,
  },
];

export const mockCredits: CreditBalance = {
  total: 5000,
  used: 1847,
  remaining: 3153,
  plan: "growth",
};

export const mockDashboardStats: DashboardStats = {
  totalAccounts: 5,
  totalFollowers: 327800,
  avgEngagementRate: 4.7,
  creditsRemaining: 3153,
  postsThisWeek: 28,
  followersGainedThisWeek: 4250,
};

export const mockActivity: ActivityItem[] = [
  {
    id: "act-1",
    type: "post_published",
    message: "Post published successfully",
    accountHandle: "@daily_meme_drop",
    timestamp: "2026-02-09T11:00:00Z",
  },
  {
    id: "act-2",
    type: "content_generated",
    message: "3 new posts generated for queue",
    accountHandle: "@ironpulse_fit",
    timestamp: "2026-02-09T10:30:00Z",
  },
  {
    id: "act-3",
    type: "engagement",
    message: "Comment replied: 'Thanks for the support!'",
    accountHandle: "@luxe_living_daily",
    timestamp: "2026-02-09T09:45:00Z",
  },
  {
    id: "act-4",
    type: "post_published",
    message: "Reel published with 1.8K likes",
    accountHandle: "@ironpulse_fit",
    timestamp: "2026-02-09T07:00:00Z",
  },
  {
    id: "act-5",
    type: "milestone",
    message: "Account reached 156K followers!",
    accountHandle: "@daily_meme_drop",
    timestamp: "2026-02-08T22:00:00Z",
  },
  {
    id: "act-6",
    type: "post_published",
    message: "Carousel published successfully",
    accountHandle: "@luxe_living_daily",
    timestamp: "2026-02-08T09:00:00Z",
  },
  {
    id: "act-7",
    type: "account_connected",
    message: "Account reconnection failed - needs reauth",
    accountHandle: "@techbyte_ai",
    timestamp: "2026-02-08T08:00:00Z",
  },
];

export const mockAnalytics: AnalyticsData = {
  followerGrowth: [
    { date: "Feb 3", followers: 315200 },
    { date: "Feb 4", followers: 316800 },
    { date: "Feb 5", followers: 318500 },
    { date: "Feb 6", followers: 320100 },
    { date: "Feb 7", followers: 322800 },
    { date: "Feb 8", followers: 325400 },
    { date: "Feb 9", followers: 327800 },
  ],
  engagementByDay: [
    { date: "Feb 3", rate: 4.2 },
    { date: "Feb 4", rate: 4.5 },
    { date: "Feb 5", rate: 3.9 },
    { date: "Feb 6", rate: 5.1 },
    { date: "Feb 7", rate: 4.8 },
    { date: "Feb 8", rate: 4.3 },
    { date: "Feb 9", rate: 4.7 },
  ],
  contentPerformance: [
    { type: "image", avgLikes: 2100, avgComments: 89, avgReach: 32000 },
    { type: "carousel", avgLikes: 3400, avgComments: 156, avgReach: 48000 },
    { type: "reel", avgLikes: 4800, avgComments: 210, avgReach: 67000 },
    { type: "story", avgLikes: 800, avgComments: 23, avgReach: 15000 },
  ],
  topPosts: [],
};
